<?php
/**
 * AddressBook
 *
 * @copyright (c) 2009, AddressBook Development Team
 * @link http://code.zikula.org/addressbook
 * @version $Id: pnadmin.php 61 2010-03-31 13:44:02Z herr.vorragend $
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package AddressBook
 * @subpackage UI
 */

class AddressBook_Controller_Admin extends Zikula_AbstractController
{

    //=========================================================================
    //  the main administration function
    //=========================================================================
    public function main()
    {
        return $this->modifyconfig();
    }

    //=========================================================================
    //  Modify the settings
    //=========================================================================
    public function modifyconfig()
    {

        // security check
        if (!(SecurityUtil::checkPermission('AddressBook::', '::', ACCESS_ADMIN))) {
            return LogUtil::registerPermissionError();
        }

        // Create output object
        $form = FormUtil::newForm('AddressBook', $this);

        // Return the output that has been generated by this function
        return $form->execute('admin/modifyconfig.tpl', new AddressBook_Handler_ModifyConfig());
    }
    
        
   /**
    * Import a CSV input
    *
    * @param array $args POST/REQUEST vars
    * @return The view var
    */
    public function importCSV($args)
    {
        $form = FormUtil::newForm($this->name, $this);
        return $form->execute('admin/importCSV.tpl', new AddressBook_Handler_ImportCSV());
    }


}
